"use client";

import { useState } from "react";
import { Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, Banknote, Bell, Building2, CalendarClock, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Database, DoorOpen, Download, LayoutDashboard, LockKeyhole, Menu, MoreHorizontal, Palette, Plus, Printer, ReceiptText, Save, Search, Settings, ShieldCheck, SlidersHorizontal, Stethoscope, TrendingUp, UserCog, UserRound, UsersRound, WalletCards, X, CircleDollarSign, ClipboardPlus, Phone, Mail, FileText, PackageCheck, CreditCard, Wrench, Monitor, Accessibility } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";

const nav = [["Visão geral", LayoutDashboard], ["Agenda", CalendarDays], ["Pacientes", UsersRound], ["Atendimentos", ClipboardPlus], ["Salas", DoorOpen], ["Financeiro", WalletCards], ["Profissionais", Stethoscope], ["Configurações", Settings]] as const;
const appointments = [
  { time: "08:00", end: "08:50", patient: "Marina Carvalho", service: "Fisioterapia", professional: "Dra. Ana Martins", room: "Sala Movimento", color: "emerald", status: "Confirmado" },
  { time: "09:00", end: "09:50", patient: "Roberto Alves", service: "Clínica médica", professional: "Dr. Paulo Mendes", room: "Consultório 1", color: "blue", status: "Aguardando" },
  { time: "10:00", end: "10:50", patient: "Clara Nogueira", service: "Psicologia", professional: "Camila Rocha", room: "Sala Acolher", color: "violet", status: "Confirmado" },
  { time: "11:00", end: "11:50", patient: "João Ribeiro", service: "Pilates", professional: "Lucas Freitas", room: "Studio Pilates", color: "amber", status: "Agendado" },
  { time: "13:30", end: "14:20", patient: "Helena Costa", service: "Fisioterapia", professional: "Dra. Ana Martins", room: "Sala Movimento", color: "emerald", status: "Confirmado" },
  { time: "14:30", end: "15:20", patient: "Pedro Matos", service: "Terapia", professional: "Camila Rocha", room: "Sala Acolher", color: "rose", status: "Agendado" },
];
const colors: Record<string, string> = { emerald: "border-l-emerald-500 bg-emerald-50/70", blue: "border-l-blue-500 bg-blue-50/70", violet: "border-l-violet-500 bg-violet-50/70", amber: "border-l-amber-500 bg-amber-50/70", rose: "border-l-rose-500 bg-rose-50/70" };

export default function Home() {
  const [active, setActive] = useState("Visão geral");
  const [mobile, setMobile] = useState(false);
  const [toast, setToast] = useState(false);
  const schedule = <DialogContent className="sm:max-w-[520px]"><DialogHeader><DialogTitle>Novo agendamento</DialogTitle><DialogDescription>Escolha paciente, atendimento, profissional e sala.</DialogDescription></DialogHeader><div className="grid gap-4 py-2"><div className="grid gap-2"><Label>Paciente</Label><Input placeholder="Buscar ou cadastrar paciente" /></div><div className="grid grid-cols-2 gap-3"><div className="grid gap-2"><Label>Modalidade</Label><Select><SelectTrigger><SelectValue placeholder="Selecionar" /></SelectTrigger><SelectContent><SelectItem value="fisio">Fisioterapia</SelectItem><SelectItem value="psico">Psicologia</SelectItem><SelectItem value="pilates">Pilates</SelectItem><SelectItem value="medica">Clínica médica</SelectItem></SelectContent></Select></div><div className="grid gap-2"><Label>Profissional</Label><Select><SelectTrigger><SelectValue placeholder="Selecionar" /></SelectTrigger><SelectContent><SelectItem value="ana">Dra. Ana Martins</SelectItem><SelectItem value="paulo">Dr. Paulo Mendes</SelectItem><SelectItem value="camila">Camila Rocha</SelectItem></SelectContent></Select></div></div><div className="grid grid-cols-2 gap-3"><div className="grid gap-2"><Label>Data</Label><Input type="date" defaultValue="2026-08-29" /></div><div className="grid gap-2"><Label>Horário</Label><Input type="time" defaultValue="15:30" /></div></div><div className="grid gap-2"><Label>Sala disponível</Label><Select><SelectTrigger><SelectValue placeholder="Selecionar sala" /></SelectTrigger><SelectContent><SelectItem value="c1">Consultório 1</SelectItem><SelectItem value="m">Sala Movimento</SelectItem><SelectItem value="a">Sala Acolher</SelectItem></SelectContent></Select></div><Button className="mt-2 h-11 bg-[#138675] hover:bg-[#0f6d60]" onClick={() => { setToast(true); setTimeout(() => setToast(false), 2600); }}>Confirmar agendamento</Button></div></DialogContent>;

  return <div className="min-h-screen bg-[#f4f7f6] text-[#18312d]">
    {mobile && <button aria-label="Fechar menu" className="fixed inset-0 z-30 bg-black/25 lg:hidden" onClick={() => setMobile(false)} />}
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[252px] flex-col border-r border-[#dce8e5] bg-[#f9fcfb] transition-transform lg:translate-x-0 ${mobile ? "translate-x-0" : "-translate-x-full"}`}><div className="flex h-20 items-center gap-3 px-6"><div className="grid size-10 place-items-center rounded-xl bg-[#138675] text-white"><Activity size={22} /></div><div><strong className="block text-[17px] tracking-tight">Recriar Gestão</strong><span className="text-xs text-[#6d817d]">Cuidado integrado</span></div><Button variant="ghost" size="icon" className="ml-auto lg:hidden" onClick={() => setMobile(false)}><X /></Button></div><nav className="space-y-1 px-3">{nav.map(([label, Icon]) => <button key={label} onClick={() => { setActive(label); setMobile(false); }} className={`flex h-11 w-full items-center gap-3 rounded-xl px-3 text-sm font-medium transition ${active === label ? "bg-[#dff3ee] text-[#087565]" : "text-[#667b76] hover:bg-[#eef5f3]"}`}><Icon size={19} />{label}</button>)}</nav><div className="mt-auto m-4 rounded-2xl border border-[#d8e9e5] bg-white p-4"><div className="mb-3 flex items-center gap-3"><div className="grid size-9 place-items-center rounded-full bg-[#e5f2ef] font-semibold text-[#138675]">EM</div><div><p className="text-sm font-semibold">Edmilson</p><p className="text-[11px] text-[#7b8d89]">Administrador</p></div></div><p className="rounded-lg bg-amber-50 px-2.5 py-2 text-[11px] leading-4 text-amber-800">Ambiente demonstrativo · use somente dados fictícios.</p></div></aside>
    <main className="lg:ml-[252px]"><header className="sticky top-0 z-20 flex h-20 items-center border-b border-[#dce8e5] bg-white/90 px-4 backdrop-blur md:px-8"><Button variant="ghost" size="icon" className="mr-2 lg:hidden" onClick={() => setMobile(true)}><Menu /></Button><div><h1 className="text-xl font-semibold tracking-tight">{active}</h1><p className="hidden text-xs text-[#758884] sm:block">Sábado, 29 de agosto de 2026</p></div><div className="ml-auto flex items-center gap-2"><div className="relative hidden sm:block"><Search className="absolute left-3 top-2.5 size-4 text-[#8ba09b]" /><Input className="w-56 rounded-xl bg-[#f5f8f7] pl-9" placeholder="Buscar paciente..." /></div><Dialog><DialogTrigger asChild><Button className="rounded-xl bg-[#138675] shadow-sm hover:bg-[#0f6d60]"><Plus /> <span className="hidden sm:inline">Novo agendamento</span><span className="sm:hidden">Agendar</span></Button></DialogTrigger>{schedule}</Dialog><button className="ml-1 grid size-10 place-items-center rounded-full bg-[#e5f2ef] font-semibold text-[#138675]">EM</button></div></header>
      <div className="mx-auto max-w-[1440px] p-4 md:p-8">{active === "Agenda" ? <AgendaSection /> : active === "Pacientes" ? <PatientsSection /> : active === "Atendimentos" ? <CareSection /> : active === "Salas" ? <RoomsSection /> : active === "Financeiro" ? <FinanceSection /> : active === "Profissionais" ? <ProfessionalsSection /> : active === "Configurações" ? <SettingsSection /> : active !== "Visão geral" ? <EmptySection title={active} onBack={() => setActive("Visão geral")} /> : <><section className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={CalendarDays} label="Atendimentos hoje" value="18" note="14 confirmados" color="emerald" /><Stat icon={Clock3} label="Aguardando" value="3" note="Próximo às 09:00" color="blue" /><Stat icon={DoorOpen} label="Salas em uso" value="4/6" note="2 disponíveis agora" color="violet" /><Stat icon={CircleDollarSign} label="Recebido hoje" value="R$ 1.840" note="3 pagamentos pendentes" color="amber" /></section>
        <section className="grid gap-6 xl:grid-cols-[1fr_360px]"><div className="rounded-2xl border border-[#dce7e4] bg-white shadow-[0_8px_30px_rgba(20,70,60,.04)]"><div className="flex flex-wrap items-center gap-3 border-b border-[#e5ecea] p-5"><div><h2 className="font-semibold">Agenda de hoje</h2><p className="text-xs text-[#7b8d89]">18 atendimentos em 6 salas</p></div><div className="ml-auto flex items-center gap-1"><Button variant="outline" size="icon" className="size-9 rounded-lg"><ChevronLeft size={16} /></Button><Button variant="outline" className="h-9 rounded-lg text-xs">Hoje</Button><Button variant="outline" size="icon" className="size-9 rounded-lg"><ChevronRight size={16} /></Button></div></div><div className="divide-y divide-[#edf1f0]">{appointments.map((a) => <article key={a.time+a.patient} className="grid grid-cols-[55px_1fr] gap-3 p-3 transition hover:bg-[#fafcfb] sm:grid-cols-[72px_1fr_auto] sm:items-center sm:p-4"><div className="text-right"><p className="text-sm font-semibold">{a.time}</p><p className="text-[10px] text-[#8b9a97]">{a.end}</p></div><div className={`rounded-xl border-l-4 p-3 ${colors[a.color]}`}><div className="flex items-center gap-2"><strong className="text-sm">{a.patient}</strong><Badge variant="outline" className="hidden bg-white/60 text-[10px] font-medium sm:inline-flex">{a.status}</Badge></div><p className="mt-1 text-xs text-[#5f7570]">{a.service} · {a.professional}</p><p className="mt-1 flex items-center gap-1 text-[11px] text-[#788c87]"><DoorOpen size={12} /> {a.room}</p></div><Button variant="ghost" size="icon" className="hidden sm:flex"><MoreHorizontal size={18} /></Button></article>)}</div><button className="w-full border-t border-[#e7eeec] p-4 text-sm font-semibold text-[#138675] hover:bg-[#f4faf8]">Ver agenda completa</button></div>
          <div className="space-y-6"><div className="rounded-2xl border border-[#dce7e4] bg-white p-5"><div className="mb-5 flex items-center"><div><h2 className="font-semibold">Ocupação das salas</h2><p className="text-xs text-[#7b8d89]">Atualizado agora</p></div><DoorOpen className="ml-auto text-[#138675]" size={20} /></div><div className="space-y-4"><Room name="Sala Movimento" service="Fisioterapia até 08:50" percent={78} /><Room name="Consultório 1" service="Livre até 09:00" percent={35} /><Room name="Sala Acolher" service="Psicologia às 10:00" percent={62} /><Room name="Studio Pilates" service="4 de 6 vagas" percent={67} /></div></div><div className="rounded-2xl bg-[#173e37] p-5 text-white shadow-lg shadow-[#173e37]/10"><p className="text-xs font-medium text-[#abd4ca]">RESUMO FINANCEIRO</p><p className="mt-2 text-2xl font-semibold">R$ 28.420,00</p><p className="text-xs text-[#b7d5ce]">Receita prevista neste mês</p><div className="my-4 h-px bg-white/15" /><div className="flex justify-between text-xs"><span className="text-[#b7d5ce]">Recebido</span><strong>R$ 21.680</strong></div><div className="mt-2 flex justify-between text-xs"><span className="text-[#b7d5ce]">Pendente</span><strong className="text-[#ffd48a]">R$ 6.740</strong></div><button onClick={() => setActive("Financeiro")} className="mt-4 w-full rounded-xl bg-white/10 py-2.5 text-xs font-semibold hover:bg-white/15">Abrir financeiro</button></div></div></section></>}</div></main>
    {toast && <div className="fixed bottom-5 right-5 z-50 rounded-xl bg-[#173e37] px-5 py-3 text-sm font-medium text-white shadow-xl">Agendamento demonstrativo criado com sucesso.</div>}
  </div>;
}

function Stat({ icon: Icon, label, value, note, color }: { icon: typeof CalendarDays; label: string; value: string; note: string; color: string }) { const c: Record<string,string> = { emerald: "bg-emerald-100 text-emerald-700", blue: "bg-blue-100 text-blue-700", violet: "bg-violet-100 text-violet-700", amber: "bg-amber-100 text-amber-700" }; return <div className="rounded-2xl border border-[#dce7e4] bg-white p-5 shadow-[0_8px_30px_rgba(20,70,60,.03)]"><div className="flex items-start"><div className={`grid size-10 place-items-center rounded-xl ${c[color]}`}><Icon size={20} /></div><span className="ml-auto text-xs font-medium text-emerald-700">Hoje</span></div><p className="mt-4 text-sm text-[#6f817d]">{label}</p><p className="mt-1 text-2xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-[11px] text-[#8a9a97]">{note}</p></div>; }
function Room({ name, service, percent }: { name: string; service: string; percent: number }) { return <div><div className="mb-2 flex items-end justify-between"><div><p className="text-sm font-semibold">{name}</p><p className="text-[11px] text-[#7b8d89]">{service}</p></div><span className="text-xs font-semibold text-[#138675]">{percent}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-[#e8f0ee]"><div className="h-full rounded-full bg-[#37a995]" style={{ width: `${percent}%` }} /></div></div>; }
function EmptySection({ title, onBack }: { title: string; onBack: () => void }) { return <div className="grid min-h-[65vh] place-items-center rounded-3xl border border-dashed border-[#cdded9] bg-white"><div className="max-w-sm p-8 text-center"><div className="mx-auto grid size-14 place-items-center rounded-2xl bg-[#e6f4f0] text-[#138675]"><UserRound /></div><h2 className="mt-5 text-xl font-semibold">Módulo de {title}</h2><p className="mt-2 text-sm leading-6 text-[#70837e]">Esta área será construída na próxima etapa. A demonstração inicial já apresenta como ela ficará integrada à agenda.</p><Button variant="outline" className="mt-5 rounded-xl" onClick={onBack}>Voltar à visão geral</Button></div></div>; }

const week = [
  { day: "SEG", date: "24", items: [{ at: "08:00", name: "Marina Carvalho", type: "Fisioterapia", room: "Movimento", tone: "emerald" }, { at: "10:00", name: "Clara Nogueira", type: "Psicologia", room: "Acolher", tone: "violet" }, { at: "14:30", name: "Pedro Matos", type: "Terapia", room: "Acolher", tone: "rose" }] },
  { day: "TER", date: "25", items: [{ at: "09:00", name: "Roberto Alves", type: "Clínica médica", room: "Consultório 1", tone: "blue" }, { at: "11:00", name: "João Ribeiro", type: "Pilates", room: "Studio", tone: "amber" }, { at: "15:30", name: "Lúcia Ferreira", type: "Fisioterapia", room: "Movimento", tone: "emerald" }] },
  { day: "QUA", date: "26", items: [{ at: "08:30", name: "Helena Costa", type: "Fisioterapia", room: "Movimento", tone: "emerald" }, { at: "13:00", name: "Miguel Dias", type: "Psicologia", room: "Acolher", tone: "violet" }] },
  { day: "QUI", date: "27", items: [{ at: "09:30", name: "Ana Luiza", type: "Pilates", room: "Studio", tone: "amber" }, { at: "13:30", name: "Carlos Prado", type: "Clínica médica", room: "Consultório 1", tone: "blue" }, { at: "16:00", name: "Beatriz Melo", type: "Terapia", room: "Acolher", tone: "rose" }] },
  { day: "SEX", date: "28", items: [{ at: "08:00", name: "Rita Moreira", type: "Fisioterapia", room: "Movimento", tone: "emerald" }, { at: "10:30", name: "Otávio Reis", type: "Pilates", room: "Studio", tone: "amber" }] },
  { day: "SÁB", date: "29", items: [{ at: "09:00", name: "Roberto Alves", type: "Clínica médica", room: "Consultório 1", tone: "blue" }, { at: "10:00", name: "Clara Nogueira", type: "Psicologia", room: "Acolher", tone: "violet" }, { at: "11:00", name: "João Ribeiro", type: "Pilates", room: "Studio", tone: "amber" }] },
];

function AgendaSection() {
  const [view, setView] = useState("Semana");
  const [professional, setProfessional] = useState("todos");
  const [room, setRoom] = useState("todas");
  return <div className="space-y-5">
    <section className="flex flex-wrap items-center gap-3 rounded-2xl border border-[#dce7e4] bg-white p-4">
      <div className="flex items-center gap-1 rounded-xl bg-[#eef4f2] p-1">{["Dia", "Semana"].map(v => <button key={v} onClick={() => setView(v)} className={`rounded-lg px-4 py-2 text-xs font-semibold transition ${view === v ? "bg-white text-[#138675] shadow-sm" : "text-[#71837f]"}`}>{v}</button>)}</div>
      <Select value={professional} onValueChange={setProfessional}><SelectTrigger className="w-[190px] rounded-xl"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="todos">Todos os profissionais</SelectItem><SelectItem value="ana">Dra. Ana Martins</SelectItem><SelectItem value="paulo">Dr. Paulo Mendes</SelectItem><SelectItem value="camila">Camila Rocha</SelectItem></SelectContent></Select>
      <Select value={room} onValueChange={setRoom}><SelectTrigger className="w-[170px] rounded-xl"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="todas">Todas as salas</SelectItem><SelectItem value="movimento">Sala Movimento</SelectItem><SelectItem value="consultorio">Consultório 1</SelectItem><SelectItem value="acolher">Sala Acolher</SelectItem><SelectItem value="studio">Studio Pilates</SelectItem></SelectContent></Select>
      <div className="ml-auto flex items-center gap-1"><Button variant="outline" size="icon" className="size-9"><ChevronLeft size={16} /></Button><Button variant="outline" className="h-9 text-xs">24–29 de agosto</Button><Button variant="outline" size="icon" className="size-9"><ChevronRight size={16} /></Button></div>
    </section>
    <div className="flex items-start gap-2 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-amber-900"><AlertTriangle className="mt-0.5 size-4 shrink-0" /><div><p className="text-xs font-semibold">Proteção contra conflitos ativada</p><p className="mt-0.5 text-[11px] text-amber-800">O sistema não permitirá o mesmo profissional ou sala em dois atendimentos simultâneos.</p></div></div>
    <section className="overflow-hidden rounded-2xl border border-[#dce7e4] bg-white shadow-[0_8px_30px_rgba(20,70,60,.04)]">
      <div className={`grid min-w-[920px] ${view === "Dia" ? "grid-cols-1" : "grid-cols-6"}`}>{(view === "Dia" ? [week[5]] : week).map((d, i) => <div key={d.day} className={`${i ? "border-l border-[#e4ecea]" : ""}`}><div className={`border-b border-[#e4ecea] p-4 text-center ${d.date === "29" ? "bg-[#e8f5f1]" : "bg-[#fafcfb]"}`}><p className="text-[10px] font-bold tracking-[.18em] text-[#80918d]">{d.day}</p><p className={`mt-1 text-xl font-semibold ${d.date === "29" ? "mx-auto grid size-9 place-items-center rounded-full bg-[#138675] text-white" : ""}`}>{d.date}</p></div><div className="min-h-[520px] space-y-3 p-2.5">{d.items.map(item => <button key={item.at+item.name} className={`w-full rounded-xl border-l-4 p-3 text-left transition hover:-translate-y-0.5 hover:shadow-md ${colors[item.tone]}`}><div className="mb-2 flex items-center justify-between"><strong className="text-xs">{item.at}</strong><MoreHorizontal size={14} className="text-[#7d8f8b]" /></div><p className="truncate text-xs font-semibold">{item.name}</p><p className="mt-1 truncate text-[10px] text-[#657b76]">{item.type}</p><p className="mt-2 flex items-center gap-1 truncate text-[10px] text-[#7b8f8a]"><DoorOpen size={11} />{item.room}</p></button>)}</div></div>)}</div>
    </section>
    <div className="flex flex-wrap gap-4 text-[11px] text-[#687b76]"><Legend color="bg-emerald-500" label="Fisioterapia" /><Legend color="bg-blue-500" label="Clínica médica" /><Legend color="bg-violet-500" label="Psicologia" /><Legend color="bg-amber-500" label="Pilates" /><Legend color="bg-rose-500" label="Terapia" /></div>
  </div>;
}
function Legend({ color, label }: { color: string; label: string }) { return <span className="flex items-center gap-1.5"><i className={`size-2 rounded-full ${color}`} />{label}</span>; }

const patients = [
  { name: "Marina Carvalho", initials: "MC", phone: "(24) 98812-3476", age: "42 anos", treatment: "Fisioterapia", professional: "Dra. Ana Martins", sessions: "7 de 10", financial: "Em dia", last: "Hoje, 08:00", color: "bg-emerald-100 text-emerald-700" },
  { name: "Roberto Alves", initials: "RA", phone: "(24) 99945-1028", age: "58 anos", treatment: "Clínica médica", professional: "Dr. Paulo Mendes", sessions: "Avulso", financial: "Pendente", last: "Hoje, 09:00", color: "bg-blue-100 text-blue-700" },
  { name: "Clara Nogueira", initials: "CN", phone: "(24) 98876-5521", age: "29 anos", treatment: "Psicologia", professional: "Camila Rocha", sessions: "4 de 8", financial: "Em dia", last: "Hoje, 10:00", color: "bg-violet-100 text-violet-700" },
  { name: "João Ribeiro", initials: "JR", phone: "(24) 99231-8840", age: "67 anos", treatment: "Pilates", professional: "Lucas Freitas", sessions: "9 de 12", financial: "Em dia", last: "Hoje, 11:00", color: "bg-amber-100 text-amber-700" },
  { name: "Helena Costa", initials: "HC", phone: "(24) 98104-7203", age: "36 anos", treatment: "Fisioterapia", professional: "Dra. Ana Martins", sessions: "2 de 10", financial: "Pendente", last: "Hoje, 13:30", color: "bg-emerald-100 text-emerald-700" },
  { name: "Pedro Matos", initials: "PM", phone: "(24) 99773-4612", age: "21 anos", treatment: "Terapia", professional: "Camila Rocha", sessions: "6 de 8", financial: "Em dia", last: "Hoje, 14:30", color: "bg-rose-100 text-rose-700" },
];

function PatientsSection() {
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("todos");
  const visible = patients.filter(p => p.name.toLowerCase().includes(query.toLowerCase()) && (filter === "todos" || (filter === "pendente" ? p.financial === "Pendente" : p.treatment === filter)));
  return <div className="space-y-5">
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><PatientStat label="Pacientes ativos" value="286" note="+12 neste mês" icon={UsersRound} /><PatientStat label="Em tratamento" value="214" note="74,8% dos pacientes" icon={Activity} /><PatientStat label="Pacotes terminando" value="18" note="Até 2 sessões restantes" icon={PackageCheck} /><PatientStat label="Com pendência" value="23" note="R$ 6.740 a receber" icon={CreditCard} /></section>
    <section className="rounded-2xl border border-[#dce7e4] bg-white shadow-[0_8px_30px_rgba(20,70,60,.04)]">
      <div className="flex flex-wrap items-center gap-3 border-b border-[#e4ecea] p-4 md:p-5"><div className="relative min-w-[220px] flex-1"><Search className="absolute left-3 top-2.5 size-4 text-[#869995]" /><Input value={query} onChange={e => setQuery(e.target.value)} className="rounded-xl bg-[#f7faf9] pl-9" placeholder="Buscar por nome do paciente..." /></div><Select value={filter} onValueChange={setFilter}><SelectTrigger className="w-[190px] rounded-xl"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="todos">Todos os pacientes</SelectItem><SelectItem value="Fisioterapia">Fisioterapia</SelectItem><SelectItem value="Psicologia">Psicologia</SelectItem><SelectItem value="Pilates">Pilates</SelectItem><SelectItem value="pendente">Pagamento pendente</SelectItem></SelectContent></Select><Button className="rounded-xl bg-[#138675] hover:bg-[#0f6d60]"><Plus /> Novo paciente</Button></div>
      <div className="hidden grid-cols-[1.4fr_.8fr_.8fr_.65fr_.6fr_36px] gap-4 border-b border-[#e9efed] bg-[#fafcfb] px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-[#7c8e89] lg:grid"><span>Paciente</span><span>Tratamento</span><span>Profissional</span><span>Pacote</span><span>Financeiro</span><span /></div>
      <div className="divide-y divide-[#e9efed]">{visible.map(p => <Sheet key={p.name}><SheetTrigger asChild><button className="grid w-full gap-3 px-4 py-4 text-left transition hover:bg-[#f7fbfa] lg:grid-cols-[1.4fr_.8fr_.8fr_.65fr_.6fr_36px] lg:items-center lg:gap-4 lg:px-5"><div className="flex items-center gap-3"><div className={`grid size-10 shrink-0 place-items-center rounded-full text-xs font-bold ${p.color}`}>{p.initials}</div><div><p className="text-sm font-semibold">{p.name}</p><p className="text-[11px] text-[#7b8d89]">{p.age} · {p.phone}</p></div></div><div><span className="lg:hidden text-[10px] text-[#879793]">Tratamento: </span><span className="text-xs font-medium">{p.treatment}</span></div><p className="text-xs text-[#657873]">{p.professional}</p><div><Badge variant="outline" className="bg-[#f7faf9] text-[10px]">{p.sessions}</Badge></div><div><Badge className={`border-0 text-[10px] ${p.financial === "Em dia" ? "bg-emerald-100 text-emerald-700" : "bg-amber-100 text-amber-800"}`}>{p.financial}</Badge></div><MoreHorizontal className="hidden text-[#899894] lg:block" size={18} /></button></SheetTrigger><PatientSheet patient={p} /></Sheet>)}</div>
      <div className="flex items-center justify-between border-t border-[#e7eeec] p-4 text-xs text-[#71837e]"><span>Exibindo {visible.length} de 286 pacientes</span><div className="flex gap-1"><Button variant="outline" size="sm" disabled>Anterior</Button><Button variant="outline" size="sm">Próxima</Button></div></div>
    </section>
  </div>;
}

function PatientStat({ label, value, note, icon: Icon }: { label: string; value: string; note: string; icon: typeof UsersRound }) { return <div className="rounded-2xl border border-[#dce7e4] bg-white p-5"><div className="flex items-start"><div><p className="text-sm text-[#6f817d]">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p><p className="mt-1 text-[11px] text-[#899995]">{note}</p></div><div className="ml-auto grid size-10 place-items-center rounded-xl bg-[#e6f4f0] text-[#138675]"><Icon size={19} /></div></div></div>; }

function PatientSheet({ patient: p }: { patient: typeof patients[number] }) { return <SheetContent className="w-full overflow-y-auto p-0 sm:max-w-[580px]"><div className="border-b border-[#e2eae8] bg-[#f4faf8] p-6"><SheetHeader><div className="flex items-center gap-4"><div className={`grid size-14 place-items-center rounded-2xl text-base font-bold ${p.color}`}>{p.initials}</div><div><SheetTitle>{p.name}</SheetTitle><SheetDescription>{p.age} · Paciente ativo</SheetDescription></div></div></SheetHeader><div className="mt-5 grid grid-cols-2 gap-2"><Button variant="outline" className="bg-white"><Phone size={15} /> Ligar</Button><Button className="bg-[#138675] hover:bg-[#0f6d60]"><CalendarDays size={15} /> Agendar</Button></div></div><Tabs defaultValue="resumo" className="p-6"><TabsList className="grid w-full grid-cols-3"><TabsTrigger value="resumo">Resumo</TabsTrigger><TabsTrigger value="historico">Histórico</TabsTrigger><TabsTrigger value="financeiro">Financeiro</TabsTrigger></TabsList><TabsContent value="resumo" className="mt-5 space-y-4"><DetailCard title="Contato"><Detail icon={Phone} text={p.phone} /><Detail icon={Mail} text="paciente@email.com" /></DetailCard><DetailCard title="Tratamento atual"><p className="text-sm font-semibold">{p.treatment}</p><p className="mt-1 text-xs text-[#72847f]">Profissional: {p.professional}</p><div className="mt-4 flex items-center justify-between rounded-xl bg-[#f5f9f8] p-3"><span className="text-xs">Sessões utilizadas</span><strong className="text-sm text-[#138675]">{p.sessions}</strong></div></DetailCard><DetailCard title="Observações importantes"><p className="text-xs leading-5 text-[#677b76]">Ficha demonstrativa. Informações clínicas detalhadas ficarão restritas aos profissionais autorizados.</p></DetailCard></TabsContent><TabsContent value="historico" className="mt-5"><DetailCard title="Últimos atendimentos">{["29/08 · Atendimento realizado", "22/08 · Evolução registrada", "15/08 · Atendimento realizado"].map((x,i) => <div key={x} className="flex gap-3 border-b border-[#e8efed] py-3 last:border-0"><div className="mt-1 size-2 rounded-full bg-[#37a995]" /><div><p className="text-xs font-medium">{x}</p><p className="mt-1 text-[11px] text-[#80918d]">{i === 1 ? "Registro disponível ao profissional" : p.professional}</p></div></div>)}</DetailCard></TabsContent><TabsContent value="financeiro" className="mt-5"><DetailCard title="Situação financeira"><div className="flex items-center justify-between"><span className="text-sm">Status atual</span><Badge className={p.financial === "Em dia" ? "bg-emerald-100 text-emerald-700" : "bg-amber-100 text-amber-800"}>{p.financial}</Badge></div><div className="mt-4 rounded-xl bg-[#f5f9f8] p-4"><p className="text-xs text-[#71837f]">Pacote contratado</p><p className="mt-1 font-semibold">{p.treatment} · {p.sessions}</p></div></DetailCard></TabsContent></Tabs></SheetContent>; }
function DetailCard({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded-2xl border border-[#e0e9e7] bg-white p-4"><h3 className="mb-3 text-xs font-bold uppercase tracking-wider text-[#71837f]">{title}</h3>{children}</div>; }
function Detail({ icon: Icon, text }: { icon: typeof Phone; text: string }) { return <div className="flex items-center gap-2 py-1.5 text-sm text-[#526963]"><Icon size={15} className="text-[#138675]" />{text}</div>; }

const careQueue = [
  { time: "08:00", name: "Marina Carvalho", type: "Fisioterapia", status: "Em atendimento", initials: "MC", color: "bg-emerald-100 text-emerald-700" },
  { time: "09:00", name: "Roberto Alves", type: "Clínica médica", status: "Aguardando", initials: "RA", color: "bg-blue-100 text-blue-700" },
  { time: "10:00", name: "Clara Nogueira", type: "Psicologia", status: "Confirmado", initials: "CN", color: "bg-violet-100 text-violet-700" },
  { time: "11:00", name: "João Ribeiro", type: "Pilates", status: "Confirmado", initials: "JR", color: "bg-amber-100 text-amber-700" },
];

function CareSection() {
  const [selected, setSelected] = useState(0);
  const [saved, setSaved] = useState(false);
  const current = careQueue[selected];
  const saveDraft = () => { setSaved(true); setTimeout(() => setSaved(false), 2400); };
  return <div className="grid gap-5 xl:grid-cols-[320px_1fr]">
    <aside className="rounded-2xl border border-[#dce7e4] bg-white"><div className="border-b border-[#e5ecea] p-4"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Fila de hoje</h2><p className="text-xs text-[#7b8d89]">4 próximos atendimentos</p></div><Badge className="bg-[#e5f4f0] text-[#138675]">Hoje</Badge></div><div className="relative mt-4"><Search className="absolute left-3 top-2.5 size-4 text-[#879994]" /><Input className="rounded-xl bg-[#f7faf9] pl-9" placeholder="Buscar na fila..." /></div></div><div className="divide-y divide-[#e9efed]">{careQueue.map((p, i) => <button key={p.name} onClick={() => setSelected(i)} className={`w-full p-4 text-left transition ${selected === i ? "bg-[#edf8f5]" : "hover:bg-[#f8fbfa]"}`}><div className="flex gap-3"><div className={`grid size-10 shrink-0 place-items-center rounded-full text-xs font-bold ${p.color}`}>{p.initials}</div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="truncate text-sm font-semibold">{p.name}</p><span className="text-xs font-bold text-[#536b65]">{p.time}</span></div><p className="mt-0.5 text-[11px] text-[#748782]">{p.type}</p><p className={`mt-2 text-[10px] font-semibold ${p.status === "Em atendimento" ? "text-emerald-700" : p.status === "Aguardando" ? "text-amber-700" : "text-[#748782]"}`}>● {p.status}</p></div></div></button>)}</div></aside>
    <section className="min-w-0 overflow-hidden rounded-2xl border border-[#dce7e4] bg-white shadow-[0_8px_30px_rgba(20,70,60,.04)]">
      <div className="flex flex-wrap items-center gap-4 border-b border-[#e4ecea] bg-[#f7fbfa] p-5"><div className={`grid size-12 place-items-center rounded-2xl font-bold ${current.color}`}>{current.initials}</div><div><h2 className="font-semibold">{current.name}</h2><p className="text-xs text-[#70847f]">{current.type} · {current.time} · Sala Movimento</p></div><Badge className="ml-auto bg-emerald-100 text-emerald-700">{current.status}</Badge></div>
      <div className="flex items-center gap-2 border-b border-[#e4ecea] bg-amber-50 px-5 py-3 text-[11px] text-amber-900"><LockKeyhole size={14} /><span><strong>Dados clínicos protegidos.</strong> Somente profissionais autorizados poderão visualizar este registro.</span></div>
      <Tabs defaultValue="evolucao" className="p-5 md:p-6"><TabsList className="grid w-full max-w-2xl grid-cols-4"><TabsTrigger value="anamnese">Anamnese</TabsTrigger><TabsTrigger value="evolucao">Evolução</TabsTrigger><TabsTrigger value="plano">Plano</TabsTrigger><TabsTrigger value="documentos">Documentos</TabsTrigger></TabsList>
        <TabsContent value="anamnese" className="mt-6 space-y-5"><FormBox title="Queixa principal"><Textarea className="min-h-24" defaultValue="Dor e limitação de movimento no ombro direito, com piora ao elevar o braço." /></FormBox><div className="grid gap-4 md:grid-cols-2"><FormBox title="Histórico do quadro"><Textarea className="min-h-28" placeholder="Início, duração e evolução dos sintomas..." /></FormBox><FormBox title="Antecedentes e cuidados"><Textarea className="min-h-28" placeholder="Cirurgias, alergias, medicações e condições anteriores..." /></FormBox></div><FormBox title="Avaliação inicial"><Textarea className="min-h-28" placeholder="Registre os dados específicos da modalidade..." /></FormBox></TabsContent>
        <TabsContent value="evolucao" className="mt-6 space-y-5"><div className="grid gap-4 md:grid-cols-3"><MiniField label="Data" value="29/08/2026" /><MiniField label="Horário" value="08:00" /><MiniField label="Profissional" value="Dra. Ana Martins" /></div><FormBox title="Evolução do atendimento"><Textarea className="min-h-40" defaultValue="Paciente compareceu referindo redução da dor. Realizados exercícios de mobilidade e fortalecimento progressivo, sem intercorrências durante a sessão." /></FormBox><div className="grid gap-4 md:grid-cols-2"><FormBox title="Condutas realizadas"><Textarea className="min-h-24" placeholder="Procedimentos, técnicas e orientações..." /></FormBox><FormBox title="Resposta do paciente"><Textarea className="min-h-24" placeholder="Evolução, tolerância e observações..." /></FormBox></div><div className="rounded-xl border border-[#dce8e5] bg-[#f7faf9] p-4 text-xs text-[#60756f]"><strong>Importante:</strong> após finalizar, o registro será mantido em ordem cronológica. Correções futuras deverão gerar histórico de alteração.</div></TabsContent>
        <TabsContent value="plano" className="mt-6 space-y-5"><FormBox title="Objetivos terapêuticos"><Textarea className="min-h-28" defaultValue="Reduzir dor, recuperar amplitude de movimento e retomar atividades funcionais sem limitação." /></FormBox><FormBox title="Plano de tratamento"><Textarea className="min-h-36" placeholder="Frequência, duração, técnicas previstas e critérios de reavaliação..." /></FormBox><div className="grid gap-4 md:grid-cols-3"><MiniField label="Frequência" value="2 vezes por semana" /><MiniField label="Sessões previstas" value="10 sessões" /><MiniField label="Reavaliação" value="Após a 5ª sessão" /></div></TabsContent>
        <TabsContent value="documentos" className="mt-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><DocumentCard title="Receita simples" note="Modelo para imprimir e assinar" /><DocumentCard title="Solicitação de exame" note="Encaminhamento para impressão" /><DocumentCard title="Declaração de comparecimento" note="Com data e horário" /><DocumentCard title="Atestado" note="Modelo para profissional autorizado" /><DocumentCard title="Relatório clínico" note="Resumo do acompanhamento" /><DocumentCard title="Plano terapêutico" note="Objetivos e condutas" /></div><div className="mt-5 rounded-xl border border-blue-200 bg-blue-50 p-4 text-xs leading-5 text-blue-900">Os documentos desta demonstração serão preparados para <strong>impressão e assinatura física</strong>. Eles não serão apresentados como prescrição digital.</div></TabsContent>
      </Tabs>
      <div className="flex flex-wrap items-center justify-end gap-2 border-t border-[#e4ecea] bg-[#fafcfb] p-4"><Button variant="outline" onClick={saveDraft}><Save size={16} /> Salvar rascunho</Button><Button className="bg-[#138675] hover:bg-[#0f6d60]"><CheckCircle2 size={16} /> Finalizar atendimento</Button></div>
    </section>{saved && <div className="fixed bottom-5 right-5 z-50 rounded-xl bg-[#173e37] px-5 py-3 text-sm font-medium text-white shadow-xl">Rascunho demonstrativo salvo.</div>}
  </div>;
}
function FormBox({ title, children }: { title: string; children: React.ReactNode }) { return <div className="grid gap-2"><Label className="text-xs font-semibold text-[#536a64]">{title}</Label>{children}</div>; }
function MiniField({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-[#dfe8e6] bg-[#f8fbfa] p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-[#82938f]">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>; }
function DocumentCard({ title, note }: { title: string; note: string }) { return <button className="rounded-2xl border border-[#dce7e4] p-4 text-left transition hover:border-[#75b7aa] hover:bg-[#f5faf8]"><div className="flex items-start"><div className="grid size-10 place-items-center rounded-xl bg-[#e5f3ef] text-[#138675]"><FileText size={19} /></div><Printer className="ml-auto text-[#8a9a96]" size={16} /></div><p className="mt-4 text-sm font-semibold">{title}</p><p className="mt-1 text-[11px] text-[#768984]">{note}</p></button>; }

const clinicRooms = [
  { name: "Sala Movimento", type: "Fisioterapia e RPG", capacity: "2 pessoas", status: "Ocupada", until: "Livre às 08:50", use: 78, icon: Activity, tone: "emerald", equipment: ["Maca", "Faixas elásticas", "Bola suíça"] },
  { name: "Consultório 1", type: "Consultas médicas", capacity: "3 pessoas", status: "Disponível", until: "Próximo às 09:00", use: 35, icon: Stethoscope, tone: "blue", equipment: ["Maca", "Computador", "Balança"] },
  { name: "Sala Acolher", type: "Psicologia e terapia", capacity: "3 pessoas", status: "Disponível", until: "Próximo às 10:00", use: 62, icon: UsersRound, tone: "violet", equipment: ["Poltronas", "Mesa de apoio", "Ar-condicionado"] },
  { name: "Studio Pilates", type: "Pilates individual e grupo", capacity: "6 pessoas", status: "Ocupada", until: "Livre às 11:50", use: 67, icon: Accessibility, tone: "amber", equipment: ["Reformer", "Cadillac", "Chair"] },
  { name: "Consultório 2", type: "Atendimento multiprofissional", capacity: "3 pessoas", status: "Disponível", until: "Livre até 13:00", use: 24, icon: Monitor, tone: "blue", equipment: ["Mesa", "Computador", "Maca"] },
  { name: "Sala Bem-estar", type: "Terapias integradas", capacity: "4 pessoas", status: "Manutenção", until: "Retorno em 31/08", use: 0, icon: Wrench, tone: "rose", equipment: ["Maca", "Armário", "Pia"] },
];

function RoomsSection() {
  const [status, setStatus] = useState("todas");
  const list = clinicRooms.filter(r => status === "todas" || r.status === status);
  return <div className="space-y-5">
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><PatientStat label="Total de salas" value="6" note="Todas cadastradas" icon={DoorOpen} /><PatientStat label="Disponíveis agora" value="3" note="Sem reservas neste horário" icon={CheckCircle2} /><PatientStat label="Em atendimento" value="2" note="Próxima liberação às 08:50" icon={Clock3} /><PatientStat label="Em manutenção" value="1" note="Sala Bem-estar" icon={Wrench} /></section>
    <div className="flex flex-wrap items-center gap-3 rounded-2xl border border-[#dce7e4] bg-white p-4"><div><h2 className="font-semibold">Ambientes da clínica</h2><p className="text-xs text-[#788a85]">Disponibilidade e ocupação em tempo real</p></div><Select value={status} onValueChange={setStatus}><SelectTrigger className="ml-auto w-[175px] rounded-xl"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="todas">Todas as salas</SelectItem><SelectItem value="Disponível">Disponíveis</SelectItem><SelectItem value="Ocupada">Ocupadas</SelectItem><SelectItem value="Manutenção">Em manutenção</SelectItem></SelectContent></Select><Dialog><DialogTrigger asChild><Button className="rounded-xl bg-[#138675] hover:bg-[#0f6d60]"><Plus /> Nova sala</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Cadastrar nova sala</DialogTitle><DialogDescription>Defina as informações e regras de utilização do ambiente.</DialogDescription></DialogHeader><div className="grid gap-4"><FormBox title="Nome da sala"><Input placeholder="Ex.: Consultório 3" /></FormBox><div className="grid grid-cols-2 gap-3"><FormBox title="Capacidade"><Input type="number" placeholder="3" /></FormBox><FormBox title="Situação"><Select><SelectTrigger><SelectValue placeholder="Selecionar" /></SelectTrigger><SelectContent><SelectItem value="ativa">Disponível</SelectItem><SelectItem value="manutencao">Manutenção</SelectItem></SelectContent></Select></FormBox></div><FormBox title="Modalidades permitidas"><Input placeholder="Fisioterapia, consulta, terapia..." /></FormBox><FormBox title="Equipamentos"><Textarea placeholder="Liste os equipamentos disponíveis" /></FormBox><Button className="bg-[#138675] hover:bg-[#0f6d60]">Salvar sala</Button></div></DialogContent></Dialog></div>
    <section className="grid gap-4 md:grid-cols-2 2xl:grid-cols-3">{list.map(room => <RoomCard key={room.name} room={room} />)}</section>
    <section className="overflow-hidden rounded-2xl border border-[#dce7e4] bg-white"><div className="flex items-center border-b border-[#e3ebe9] p-5"><div><h2 className="font-semibold">Mapa de ocupação de hoje</h2><p className="text-xs text-[#788a85]">Horários reservados por sala</p></div><Button variant="outline" className="ml-auto"><CalendarDays size={15} /> Ver semana</Button></div><div className="overflow-x-auto"><div className="min-w-[850px]"><div className="grid grid-cols-[170px_repeat(6,1fr)] border-b border-[#e4ecea] bg-[#fafcfb] text-center text-[10px] font-bold text-[#788b86]"><span className="p-3 text-left">SALA</span>{["08:00", "10:00", "12:00", "14:00", "16:00", "18:00"].map(x => <span key={x} className="border-l border-[#e4ecea] p-3">{x}</span>)}</div>{clinicRooms.map((r,i) => <div key={r.name} className="grid grid-cols-[170px_repeat(6,1fr)] border-b border-[#edf1f0] last:border-0"><div className="p-3"><p className="text-xs font-semibold">{r.name}</p><p className="text-[10px] text-[#879793]">{r.capacity}</p></div>{[0,1,2,3,4,5].map(n => <div key={n} className="border-l border-[#edf1f0] p-2"><div className={`h-8 rounded-lg ${r.status === "Manutenção" ? "bg-rose-100" : (n+i)%3 === 0 ? "bg-[#bfe5dc]" : (n+i)%4 === 0 ? "bg-amber-100" : "bg-[#f5f8f7]"}`} /></div>)}</div>)}</div></div><div className="flex gap-5 border-t border-[#e4ecea] p-4 text-[11px] text-[#6e817c]"><Legend color="bg-[#7bc8b6]" label="Reservado" /><Legend color="bg-[#fef3c7]" label="Bloqueado" /><Legend color="bg-rose-200" label="Manutenção" /><Legend color="bg-[#f0f4f3]" label="Disponível" /></div></section>
  </div>;
}

function RoomCard({ room }: { room: typeof clinicRooms[number] }) {
  const Icon = room.icon; const tone: Record<string,string> = { emerald: "bg-emerald-100 text-emerald-700", blue: "bg-blue-100 text-blue-700", violet: "bg-violet-100 text-violet-700", amber: "bg-amber-100 text-amber-700", rose: "bg-rose-100 text-rose-700" };
  return <article className="rounded-2xl border border-[#dce7e4] bg-white p-5 transition hover:-translate-y-0.5 hover:shadow-lg hover:shadow-[#244f46]/5"><div className="flex items-start"><div className={`grid size-11 place-items-center rounded-xl ${tone[room.tone]}`}><Icon size={20} /></div><div className="ml-3"><h3 className="text-sm font-semibold">{room.name}</h3><p className="text-[11px] text-[#788a85]">{room.type}</p></div><Badge className={`ml-auto border-0 text-[10px] ${room.status === "Disponível" ? "bg-emerald-100 text-emerald-700" : room.status === "Ocupada" ? "bg-blue-100 text-blue-700" : "bg-rose-100 text-rose-700"}`}>{room.status}</Badge></div><div className="my-4 grid grid-cols-2 gap-2"><div className="rounded-xl bg-[#f7faf9] p-3"><p className="text-[10px] text-[#81918d]">CAPACIDADE</p><p className="mt-1 text-xs font-semibold">{room.capacity}</p></div><div className="rounded-xl bg-[#f7faf9] p-3"><p className="text-[10px] text-[#81918d]">PRÓXIMO STATUS</p><p className="mt-1 text-xs font-semibold">{room.until}</p></div></div><p className="text-[10px] font-bold uppercase tracking-wide text-[#81918d]">Equipamentos</p><div className="mt-2 flex flex-wrap gap-1.5">{room.equipment.map(e => <Badge key={e} variant="outline" className="bg-white text-[10px] font-medium">{e}</Badge>)}</div><div className="mt-4"><div className="mb-1.5 flex justify-between text-[10px] text-[#71847f]"><span>Ocupação hoje</span><strong>{room.use}%</strong></div><div className="h-1.5 rounded-full bg-[#e9efed]"><div className={`h-full rounded-full ${room.status === "Manutenção" ? "bg-rose-400" : "bg-[#37a995]"}`} style={{width:`${room.use}%`}} /></div></div><div className="mt-4 grid grid-cols-2 gap-2"><Button variant="outline" size="sm"><CalendarDays size={14} /> Agenda</Button><Button variant="outline" size="sm"><Wrench size={14} /> Bloquear</Button></div></article>;
}

const transactions = [
  { date: "29/08", name: "Marina Carvalho", desc: "Pacote Fisioterapia · 10 sessões", method: "Pix", value: "R$ 850,00", status: "Pago", kind: "in" },
  { date: "29/08", name: "Roberto Alves", desc: "Consulta clínica", method: "Cartão", value: "R$ 180,00", status: "Pendente", kind: "in" },
  { date: "29/08", name: "Clara Nogueira", desc: "Sessão de psicologia", method: "Pix", value: "R$ 140,00", status: "Pago", kind: "in" },
  { date: "28/08", name: "Fornecedor Saúde", desc: "Materiais de fisioterapia", method: "Boleto", value: "− R$ 420,00", status: "Pago", kind: "out" },
  { date: "28/08", name: "João Ribeiro", desc: "Pacote Pilates · 12 sessões", method: "Cartão", value: "R$ 620,00", status: "Pago", kind: "in" },
  { date: "27/08", name: "Energia elétrica", desc: "Conta mensal da clínica", method: "Débito", value: "− R$ 1.240,00", status: "Agendado", kind: "out" },
];

function FinanceSection() {
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center gap-3"><div><h2 className="font-semibold">Resumo financeiro</h2><p className="text-xs text-[#758883]">Movimentação demonstrativa de agosto de 2026</p></div><Select defaultValue="agosto"><SelectTrigger className="ml-auto w-[165px] rounded-xl bg-white"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="agosto">Agosto de 2026</SelectItem><SelectItem value="julho">Julho de 2026</SelectItem></SelectContent></Select><Button variant="outline"><Download size={15} /> Exportar</Button><Dialog><DialogTrigger asChild><Button className="bg-[#138675] hover:bg-[#0f6d60]"><Plus /> Novo lançamento</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Novo lançamento financeiro</DialogTitle><DialogDescription>Registre uma entrada, despesa ou conta futura.</DialogDescription></DialogHeader><div className="grid gap-4"><div className="grid grid-cols-2 gap-3"><FormBox title="Tipo"><Select><SelectTrigger><SelectValue placeholder="Selecionar" /></SelectTrigger><SelectContent><SelectItem value="receita">Receita</SelectItem><SelectItem value="despesa">Despesa</SelectItem></SelectContent></Select></FormBox><FormBox title="Vencimento"><Input type="date" /></FormBox></div><FormBox title="Descrição"><Input placeholder="Descrição do lançamento" /></FormBox><div className="grid grid-cols-2 gap-3"><FormBox title="Valor"><Input placeholder="R$ 0,00" /></FormBox><FormBox title="Forma de pagamento"><Select><SelectTrigger><SelectValue placeholder="Selecionar" /></SelectTrigger><SelectContent><SelectItem value="pix">Pix</SelectItem><SelectItem value="cartao">Cartão</SelectItem><SelectItem value="dinheiro">Dinheiro</SelectItem><SelectItem value="boleto">Boleto</SelectItem></SelectContent></Select></FormBox></div><Button className="bg-[#138675] hover:bg-[#0f6d60]">Salvar lançamento</Button></div></DialogContent></Dialog></div>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><FinanceCard title="Receita do mês" value="R$ 28.420" note="+12,4% sobre julho" icon={ArrowUpRight} tone="emerald" /><FinanceCard title="Despesas do mês" value="R$ 9.760" note="34,3% da receita" icon={ArrowDownRight} tone="rose" /><FinanceCard title="A receber" value="R$ 6.740" note="23 pagamentos pendentes" icon={Clock3} tone="amber" /><FinanceCard title="Saldo previsto" value="R$ 18.660" note="Receitas menos despesas" icon={TrendingUp} tone="blue" /></section>
    <section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><div className="rounded-2xl border border-[#dce7e4] bg-white p-5"><div className="flex items-center"><div><h3 className="font-semibold">Receitas e despesas</h3><p className="text-xs text-[#788b86]">Evolução dos últimos 6 meses</p></div><div className="ml-auto flex gap-3 text-[10px]"><Legend color="bg-[#37a995]" label="Receitas" /><Legend color="bg-rose-400" label="Despesas" /></div></div><div className="mt-8 flex h-52 items-end justify-around gap-3 border-b border-[#dfe8e6] px-2">{[{m:"MAR",a:56,b:24},{m:"ABR",a:68,b:30},{m:"MAI",a:62,b:28},{m:"JUN",a:78,b:34},{m:"JUL",a:72,b:31},{m:"AGO",a:92,b:36}].map(x => <div key={x.m} className="flex h-full flex-1 flex-col justify-end"><div className="mx-auto flex h-[170px] items-end gap-1"><div className="w-4 rounded-t bg-[#37a995] sm:w-6" style={{height:`${x.a}%`}} /><div className="w-4 rounded-t bg-rose-300 sm:w-6" style={{height:`${x.b}%`}} /></div><p className="mt-2 text-center text-[9px] font-bold text-[#82938f]">{x.m}</p></div>)}</div></div>
      <div className="rounded-2xl border border-[#dce7e4] bg-white p-5"><h3 className="font-semibold">Formas de pagamento</h3><p className="text-xs text-[#788b86]">Recebimentos no mês</p><div className="mx-auto my-6 grid size-40 place-items-center rounded-full" style={{background:"conic-gradient(#138675 0 45%, #5ba9d6 45% 73%, #f0b958 73% 90%, #c6d4d1 90%)"}}><div className="grid size-24 place-items-center rounded-full bg-white text-center"><div><p className="text-xl font-semibold">R$ 28,4k</p><p className="text-[9px] text-[#82938f]">TOTAL</p></div></div></div><div className="grid grid-cols-2 gap-3 text-[11px]"><PaymentDot color="bg-[#138675]" label="Pix" value="45%" /><PaymentDot color="bg-[#5ba9d6]" label="Cartão" value="28%" /><PaymentDot color="bg-[#f0b958]" label="Dinheiro" value="17%" /><PaymentDot color="bg-[#c6d4d1]" label="Outros" value="10%" /></div></div></section>
    <Tabs defaultValue="movimentos" className="rounded-2xl border border-[#dce7e4] bg-white"><div className="flex flex-wrap items-center gap-3 border-b border-[#e4ecea] p-4"><TabsList><TabsTrigger value="movimentos">Movimentações</TabsTrigger><TabsTrigger value="contas">Contas a pagar</TabsTrigger><TabsTrigger value="pacotes">Pacotes</TabsTrigger><TabsTrigger value="repasses">Repasses</TabsTrigger></TabsList><div className="relative ml-auto hidden md:block"><Search className="absolute left-3 top-2.5 size-4 text-[#899b96]" /><Input className="w-56 pl-9" placeholder="Buscar lançamento..." /></div></div><TabsContent value="movimentos" className="m-0"><TransactionList /></TabsContent><TabsContent value="contas" className="m-0"><SimpleFinanceTable rows={[["Energia elétrica","31/08/2026","R$ 1.240,00","Agendado"],["Aluguel da clínica","05/09/2026","R$ 4.800,00","Pendente"],["Materiais de escritório","08/09/2026","R$ 380,00","Pendente"]]} /></TabsContent><TabsContent value="pacotes" className="m-0"><SimpleFinanceTable rows={[["Marina Carvalho","Fisioterapia · 10 sessões","R$ 850,00","7 utilizadas"],["João Ribeiro","Pilates · 12 sessões","R$ 620,00","9 utilizadas"],["Clara Nogueira","Psicologia · 8 sessões","R$ 960,00","4 utilizadas"]]} /></TabsContent><TabsContent value="repasses" className="m-0"><SimpleFinanceTable rows={[["Dra. Ana Martins","22 atendimentos","R$ 3.740,00","A calcular"],["Dr. Paulo Mendes","16 atendimentos","R$ 2.560,00","A calcular"],["Camila Rocha","19 atendimentos","R$ 2.850,00","A calcular"]]} /></TabsContent></Tabs>
  </div>;
}
function FinanceCard({ title, value, note, icon: Icon, tone }: { title:string; value:string; note:string; icon:typeof ArrowUpRight; tone:string }) { const c:Record<string,string>={emerald:"bg-emerald-100 text-emerald-700",rose:"bg-rose-100 text-rose-700",amber:"bg-amber-100 text-amber-700",blue:"bg-blue-100 text-blue-700"}; return <div className="rounded-2xl border border-[#dce7e4] bg-white p-5"><div className="flex"><div className={`grid size-10 place-items-center rounded-xl ${c[tone]}`}><Icon size={19}/></div><Badge variant="outline" className="ml-auto h-6 bg-[#fafcfb] text-[10px]">Agosto</Badge></div><p className="mt-4 text-sm text-[#70827d]">{title}</p><p className="mt-1 text-2xl font-semibold">{value}</p><p className="mt-1 text-[11px] text-[#879793]">{note}</p></div>; }
function PaymentDot({color,label,value}:{color:string;label:string;value:string}) { return <div className="flex items-center gap-2"><i className={`size-2 rounded-full ${color}`} /><span>{label}</span><strong className="ml-auto">{value}</strong></div>; }
function TransactionList() { return <div><div className="hidden grid-cols-[70px_1.2fr_1.5fr_.7fr_.7fr_.65fr] gap-3 bg-[#fafcfb] px-5 py-3 text-[10px] font-bold uppercase tracking-wide text-[#7b8d88] lg:grid"><span>Data</span><span>Cliente/Fornecedor</span><span>Descrição</span><span>Forma</span><span>Valor</span><span>Status</span></div>{transactions.map((t,i)=><div key={i} className="grid gap-2 border-t border-[#e9efed] px-5 py-4 text-xs lg:grid-cols-[70px_1.2fr_1.5fr_.7fr_.7fr_.65fr] lg:items-center lg:gap-3"><span className="text-[#788b86]">{t.date}</span><strong>{t.name}</strong><span className="text-[#667b75]">{t.desc}</span><Badge variant="outline" className="w-fit text-[10px]">{t.method}</Badge><strong className={t.kind==="out"?"text-rose-600":"text-emerald-700"}>{t.value}</strong><Badge className={`w-fit border-0 text-[10px] ${t.status==="Pago"?"bg-emerald-100 text-emerald-700":t.status==="Pendente"?"bg-amber-100 text-amber-800":"bg-blue-100 text-blue-700"}`}>{t.status}</Badge></div>)}</div>; }
function SimpleFinanceTable({rows}:{rows:string[][]}) { return <div>{rows.map((r,i)=><div key={i} className="grid gap-2 border-t border-[#e9efed] px-5 py-4 text-xs md:grid-cols-4 md:items-center">{r.map((x,n)=><span key={n} className={n===0?"font-semibold":"text-[#667b75]"}>{x}</span>)}</div>)}</div>; }

const professionals = [
  { name:"Dra. Ana Martins", initials:"AM", role:"Fisioterapeuta", council:"CREFITO 2 · 123456-F", modes:["Fisioterapia","RPG"], today:"6 atendimentos", week:"Seg, Qua e Sex", hours:"08:00–17:00", repasse:"45%", color:"bg-emerald-100 text-emerald-700", status:"Em atendimento" },
  { name:"Dr. Paulo Mendes", initials:"PM", role:"Clínico geral", council:"CRM-RJ · 987654", modes:["Consulta","Retorno"], today:"4 atendimentos", week:"Ter, Qui e Sáb", hours:"09:00–15:00", repasse:"50%", color:"bg-blue-100 text-blue-700", status:"Disponível" },
  { name:"Camila Rocha", initials:"CR", role:"Psicóloga", council:"CRP 05 · 56789", modes:["Psicologia","Terapia"], today:"5 atendimentos", week:"Seg a Sex", hours:"10:00–19:00", repasse:"50%", color:"bg-violet-100 text-violet-700", status:"Em atendimento" },
  { name:"Lucas Freitas", initials:"LF", role:"Fisioterapeuta / Pilates", council:"CREFITO 2 · 246810-F", modes:["Pilates","Fisioterapia"], today:"3 atendimentos", week:"Ter a Sáb", hours:"07:00–13:00", repasse:"40%", color:"bg-amber-100 text-amber-700", status:"Disponível" },
];

function ProfessionalsSection(){
 const [query,setQuery]=useState(""); const visible=professionals.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())||p.role.toLowerCase().includes(query.toLowerCase()));
 return <div className="space-y-5"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><PatientStat label="Profissionais ativos" value="12" note="Equipe multidisciplinar" icon={UsersRound}/><PatientStat label="Atendendo agora" value="4" note="Em 4 salas diferentes" icon={Activity}/><PatientStat label="Agenda hoje" value="18" note="14 confirmados" icon={CalendarClock}/><PatientStat label="Acessos ativos" value="11" note="1 convite pendente" icon={ShieldCheck}/></section>
 <div className="flex flex-wrap items-center gap-3 rounded-2xl border border-[#dce7e4] bg-white p-4"><div className="relative min-w-[230px] flex-1"><Search className="absolute left-3 top-2.5 size-4 text-[#899b96]"/><Input value={query} onChange={e=>setQuery(e.target.value)} className="pl-9" placeholder="Buscar profissional ou especialidade..."/></div><Select defaultValue="todos"><SelectTrigger className="w-[180px]"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="todos">Todas as áreas</SelectItem><SelectItem value="medicina">Medicina</SelectItem><SelectItem value="fisioterapia">Fisioterapia</SelectItem><SelectItem value="psicologia">Psicologia</SelectItem></SelectContent></Select><Dialog><DialogTrigger asChild><Button className="bg-[#138675] hover:bg-[#0f6d60]"><Plus/> Novo profissional</Button></DialogTrigger><DialogContent className="sm:max-w-[560px]"><DialogHeader><DialogTitle>Cadastrar profissional</DialogTitle><DialogDescription>Defina os dados, agenda, acesso e regra de repasse.</DialogDescription></DialogHeader><div className="grid gap-4"><div className="grid grid-cols-2 gap-3"><FormBox title="Nome completo"><Input placeholder="Nome do profissional"/></FormBox><FormBox title="Especialidade"><Input placeholder="Ex.: Fisioterapia"/></FormBox></div><div className="grid grid-cols-2 gap-3"><FormBox title="Conselho"><Input placeholder="CREFITO, CRM, CRP..."/></FormBox><FormBox title="Número"><Input placeholder="Registro profissional"/></FormBox></div><div className="grid grid-cols-2 gap-3"><FormBox title="Início do expediente"><Input type="time"/></FormBox><FormBox title="Fim do expediente"><Input type="time"/></FormBox></div><FormBox title="Modalidades atendidas"><Input placeholder="Consulta, retorno, fisioterapia..."/></FormBox><FormBox title="Regra de repasse"><Input placeholder="Ex.: 45% por atendimento"/></FormBox><Button className="bg-[#138675] hover:bg-[#0f6d60]">Salvar profissional</Button></div></DialogContent></Dialog></div>
 <section className="grid gap-4 lg:grid-cols-2">{visible.map(p=><ProfessionalCard key={p.name} p={p}/>)}</section>
 <section className="rounded-2xl border border-[#dce7e4] bg-white"><div className="flex items-center border-b border-[#e3ebe9] p-5"><div><h3 className="font-semibold">Disponibilidade semanal</h3><p className="text-xs text-[#788a85]">Visão resumida da equipe</p></div><Button variant="outline" className="ml-auto"><CalendarDays size={15}/> Configurar horários</Button></div><div className="overflow-x-auto"><div className="min-w-[800px]"><div className="grid grid-cols-[200px_repeat(6,1fr)] bg-[#fafcfb] text-center text-[10px] font-bold text-[#778a85]"><span className="p-3 text-left">PROFISSIONAL</span>{["SEG","TER","QUA","QUI","SEX","SÁB"].map(d=><span key={d} className="border-l border-[#e4ecea] p-3">{d}</span>)}</div>{professionals.map((p,i)=><div key={p.name} className="grid grid-cols-[200px_repeat(6,1fr)] border-t border-[#e9efed]"><div className="p-3"><p className="text-xs font-semibold">{p.name}</p><p className="text-[10px] text-[#82938f]">{p.hours}</p></div>{[0,1,2,3,4,5].map(d=><div key={d} className="grid place-items-center border-l border-[#e9efed] p-2"><div className={`h-7 w-full rounded-lg ${(d+i)%2===0||i===2?"bg-[#cceae3]":"bg-[#f3f7f6]"}`}/></div>)}</div>)}</div></div><div className="flex gap-5 border-t border-[#e4ecea] p-4"><Legend color="bg-[#89cdbc]" label="Disponível"/><Legend color="bg-[#eef4f2]" label="Sem expediente"/></div></section></div>;
}
function ProfessionalCard({p}:{p:typeof professionals[number]}){return <Sheet><SheetTrigger asChild><button className="rounded-2xl border border-[#dce7e4] bg-white p-5 text-left transition hover:-translate-y-0.5 hover:shadow-lg hover:shadow-[#244f46]/5"><div className="flex items-start"><div className={`grid size-12 place-items-center rounded-2xl font-bold ${p.color}`}>{p.initials}</div><div className="ml-3"><h3 className="text-sm font-semibold">{p.name}</h3><p className="text-[11px] text-[#6f837d]">{p.role}</p><p className="mt-1 text-[10px] text-[#899995]">{p.council}</p></div><Badge className={`ml-auto text-[10px] ${p.status==="Disponível"?"bg-emerald-100 text-emerald-700":"bg-blue-100 text-blue-700"}`}>{p.status}</Badge></div><div className="my-4 flex flex-wrap gap-1.5">{p.modes.map(m=><Badge key={m} variant="outline" className="text-[10px]">{m}</Badge>)}</div><div className="grid grid-cols-3 gap-2"><MiniMetric label="HOJE" value={p.today}/><MiniMetric label="HORÁRIO" value={p.hours}/><MiniMetric label="REPASSE" value={p.repasse}/></div></button></SheetTrigger><ProfessionalSheet p={p}/></Sheet>}
function MiniMetric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-[#f6f9f8] p-3"><p className="text-[9px] font-bold text-[#879793]">{label}</p><p className="mt-1 truncate text-[11px] font-semibold">{value}</p></div>}
function ProfessionalSheet({p}:{p:typeof professionals[number]}){return <SheetContent className="w-full overflow-y-auto sm:max-w-[560px]"><SheetHeader><div className="flex items-center gap-4"><div className={`grid size-14 place-items-center rounded-2xl font-bold ${p.color}`}>{p.initials}</div><div><SheetTitle>{p.name}</SheetTitle><SheetDescription>{p.role} · {p.council}</SheetDescription></div></div></SheetHeader><Tabs defaultValue="agenda" className="mt-6"><TabsList className="grid w-full grid-cols-3"><TabsTrigger value="agenda">Agenda</TabsTrigger><TabsTrigger value="acesso">Permissões</TabsTrigger><TabsTrigger value="repasse">Repasse</TabsTrigger></TabsList><TabsContent value="agenda" className="mt-5 space-y-4"><DetailCard title="Disponibilidade"><Detail icon={CalendarDays} text={p.week}/><Detail icon={Clock3} text={p.hours}/></DetailCard><DetailCard title="Atendimentos de hoje">{["08:00 · Marina Carvalho","10:30 · Helena Costa","14:00 · Pedro Matos"].map(x=><p key={x} className="border-b border-[#e8efed] py-3 text-xs last:border-0">{x}</p>)}</DetailCard></TabsContent><TabsContent value="acesso" className="mt-5"><DetailCard title="Permissões do sistema"><Permission label="Visualizar própria agenda" checked/><Permission label="Criar agendamentos" checked/><Permission label="Acessar prontuários atribuídos" checked/><Permission label="Visualizar financeiro geral"/><Permission label="Editar usuários e permissões"/></DetailCard></TabsContent><TabsContent value="repasse" className="mt-5"><DetailCard title="Regra atual"><p className="text-2xl font-semibold text-[#138675]">{p.repasse}</p><p className="mt-1 text-xs text-[#768984]">Sobre atendimentos realizados e recebidos</p><div className="mt-4 rounded-xl bg-[#f5f9f8] p-4"><p className="text-xs text-[#758883]">Estimativa do mês</p><p className="mt-1 text-lg font-semibold">R$ 3.740,00</p></div></DetailCard></TabsContent></Tabs></SheetContent>}
function Permission({label,checked=false}:{label:string;checked?:boolean}){return <div className="flex items-center justify-between border-b border-[#e8efed] py-3 last:border-0"><span className="text-xs">{label}</span><Switch defaultChecked={checked}/></div>}

const settingNav=[["Dados da clínica",Building2],["Modalidades",Stethoscope],["Agenda e horários",CalendarClock],["Pacotes e pagamentos",WalletCards],["Usuários e acessos",UserCog],["Notificações",Bell],["Segurança e LGPD",ShieldCheck],["Aparência",Palette]] as const;
function SettingsSection(){const [section,setSection]=useState("Dados da clínica");const [saved,setSaved]=useState(false);const save=()=>{setSaved(true);setTimeout(()=>setSaved(false),2200)};return <div className="grid gap-5 xl:grid-cols-[260px_1fr]"><aside className="h-fit rounded-2xl border border-[#dce7e4] bg-white p-2">{settingNav.map(([name,Icon])=><button key={name} onClick={()=>setSection(name)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-xs font-medium transition ${section===name?"bg-[#e5f4f0] text-[#087565]":"text-[#667b76] hover:bg-[#f4f8f7]"}`}><Icon size={17}/>{name}</button>)}</aside><section className="overflow-hidden rounded-2xl border border-[#dce7e4] bg-white"><div className="flex items-center border-b border-[#e4ecea] bg-[#fafcfb] p-5"><div><h2 className="font-semibold">{section}</h2><p className="text-xs text-[#788b86]">Configurações gerais da demonstração</p></div><Button onClick={save} className="ml-auto bg-[#138675] hover:bg-[#0f6d60]"><Save size={15}/> Salvar alterações</Button></div><div className="p-5 md:p-6"><SettingsContent section={section}/></div></section>{saved&&<div className="fixed bottom-5 right-5 z-50 rounded-xl bg-[#173e37] px-5 py-3 text-sm font-medium text-white shadow-xl">Configurações demonstrativas salvas.</div>}</div>}
function SettingsContent({section}:{section:string}){
 if(section==="Dados da clínica")return <div className="space-y-6"><div className="flex items-center gap-4 rounded-2xl bg-[#f5faf8] p-4"><div className="grid size-16 place-items-center rounded-2xl bg-[#138675] text-white"><Activity size={28}/></div><div><p className="text-sm font-semibold">Identidade da clínica</p><p className="text-xs text-[#71847f]">Logo, nome e dados institucionais</p><Button variant="outline" size="sm" className="mt-2 bg-white">Alterar logotipo</Button></div></div><div className="grid gap-4 md:grid-cols-2"><FormBox title="Nome da clínica"><Input defaultValue="Clínica Recriar"/></FormBox><FormBox title="CNPJ"><Input placeholder="00.000.000/0000-00"/></FormBox><FormBox title="Telefone"><Input defaultValue="(24) 2017-3540"/></FormBox><FormBox title="E-mail"><Input defaultValue="contato@clinicarecriar.com.br"/></FormBox></div><FormBox title="Endereço"><Input defaultValue="Estrada União e Indústria, Nogueira — Petrópolis/RJ"/></FormBox></div>;
 if(section==="Modalidades")return <SettingList rows={[["Fisioterapia","50 minutos · R$ 120,00"],["Clínica médica","50 minutos · R$ 180,00"],["Psicologia","50 minutos · R$ 140,00"],["Pilates","50 minutos · até 6 pessoas"],["Terapia integrada","50 minutos · R$ 130,00"]]} button="Nova modalidade"/>;
 if(section==="Agenda e horários")return <div className="space-y-5"><DetailCard title="Funcionamento geral">{[["Segunda a sexta","07:00 às 20:00"],["Sábado","08:00 às 14:00"],["Domingo","Fechado"]].map(r=><div key={r[0]} className="grid grid-cols-2 border-b border-[#e8efed] py-3 text-xs last:border-0"><strong>{r[0]}</strong><span>{r[1]}</span></div>)}</DetailCard><DetailCard title="Regras da agenda"><Permission label="Bloquear conflito de profissional" checked/><Permission label="Bloquear conflito de sala" checked/><Permission label="Permitir encaixes pela recepção" checked/><Permission label="Permitir agendamento retroativo"/><Permission label="Exigir confirmação do paciente" checked/></DetailCard></div>;
 if(section==="Pacotes e pagamentos")return <div className="space-y-5"><SettingList rows={[["Fisioterapia · 10 sessões","R$ 850,00 · validade de 90 dias"],["Psicologia · 8 sessões","R$ 960,00 · validade de 60 dias"],["Pilates · 12 sessões","R$ 620,00 · validade de 45 dias"]]} button="Novo pacote"/><DetailCard title="Formas aceitas"><Permission label="Pix" checked/><Permission label="Cartão de crédito" checked/><Permission label="Cartão de débito" checked/><Permission label="Dinheiro" checked/><Permission label="Boleto"/></DetailCard></div>;
 if(section==="Usuários e acessos")return <SettingList rows={[["Edmilson","Administrador · acesso completo"],["Recepção","Agenda, pacientes e pagamentos"],["Dra. Ana Martins","Agenda e prontuários atribuídos"],["Camila Rocha","Agenda e prontuários atribuídos"]]} button="Convidar usuário"/>;
 if(section==="Notificações")return <DetailCard title="Avisos automáticos"><Permission label="Lembrete de consulta ao paciente" checked/><Permission label="Aviso de pacote terminando" checked/><Permission label="Alerta de pagamento pendente" checked/><Permission label="Aviso de alteração na agenda" checked/><Permission label="Resumo financeiro diário"/></DetailCard>;
 if(section==="Segurança e LGPD")return <div className="space-y-5"><div className="flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900"><ShieldCheck className="shrink-0" size={19}/><p>Antes do uso real, será necessário revisar bases legais, política de privacidade, retenção, backups e resposta a incidentes.</p></div><DetailCard title="Proteções"><Permission label="Login individual obrigatório" checked/><Permission label="Registrar acessos a prontuários" checked/><Permission label="Histórico de alterações clínicas" checked/><Permission label="Encerrar sessões inativas" checked/><Permission label="Autenticação em duas etapas"/></DetailCard><DetailCard title="Dados e continuidade"><SettingLine icon={Database} title="Backup automático" note="Configurar antes do uso real"/><SettingLine icon={FileText} title="Política de privacidade" note="Documento pendente de revisão"/><SettingLine icon={Download} title="Exportação de dados do paciente" note="Prevista para a versão operacional"/></DetailCard></div>;
 return <div className="space-y-5"><DetailCard title="Tema do sistema"><div className="grid grid-cols-3 gap-3">{["Verde Recriar","Azul sereno","Neutro"].map((x,i)=><button key={x} className={`rounded-xl border p-4 text-xs font-semibold ${i===0?"border-[#138675] bg-[#edf8f5]":"border-[#dfe8e6]"}`}><i className={`mx-auto mb-3 block size-8 rounded-full ${i===0?"bg-[#138675]":i===1?"bg-blue-500":"bg-slate-500"}`}/>{x}</button>)}</div></DetailCard><DetailCard title="Exibição"><Permission label="Menu lateral compacto"/><Permission label="Mostrar valores no painel inicial" checked/><Permission label="Usar animações suaves" checked/></DetailCard></div>;
}
function SettingList({rows,button}:{rows:string[][];button:string}){return <div><div className="space-y-2">{rows.map(r=><div key={r[0]} className="flex items-center gap-3 rounded-xl border border-[#e0e9e7] p-4"><div className="grid size-9 place-items-center rounded-lg bg-[#e8f5f1] text-[#138675]"><SlidersHorizontal size={16}/></div><div><p className="text-xs font-semibold">{r[0]}</p><p className="text-[11px] text-[#788b86]">{r[1]}</p></div><Button variant="ghost" size="icon" className="ml-auto"><MoreHorizontal size={17}/></Button></div>)}</div><Button variant="outline" className="mt-4"><Plus size={15}/>{button}</Button></div>}
function SettingLine({icon:Icon,title,note}:{icon:typeof Database;title:string;note:string}){return <div className="flex items-center gap-3 border-b border-[#e8efed] py-3 last:border-0"><Icon size={17} className="text-[#138675]"/><div><p className="text-xs font-semibold">{title}</p><p className="text-[10px] text-[#80918d]">{note}</p></div><ChevronRight className="ml-auto text-[#91a09c]" size={16}/></div>}
